# Generated by Django 5.2.4 on 2025-07-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diskuze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=200, verbose_name='Název diskuze')),
                ('popis', models.TextField(blank=True, null=True, verbose_name='Popis diskuze')),
                ('datum_zahajeni', models.DateTimeField(auto_now_add=True, verbose_name='Datum zahájení diskuze')),
            ],
            options={
                'verbose_name': 'Diskuze',
                'verbose_name_plural': 'Diskuze',
                'ordering': ['-datum_zahajeni'],
            },
        ),
        migrations.CreateModel(
            name='Zprava',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=200, verbose_name='Název zprávy')),
                ('obsah', models.TextField(verbose_name='Obsah zprávy')),
                ('datum_vytvoreni', models.DateTimeField(auto_now_add=True, verbose_name='Datum vytvoření')),
            ],
            options={
                'verbose_name': 'Zpráva',
                'verbose_name_plural': 'Zprávy',
            },
        ),
    ]
