# Generated by Django 5.2.4 on 2025-07-26 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diskuze', '0001_initial'),
        ('pages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='diskuze',
            name='clanek',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diskuze_ke_clanku', to='pages.page', verbose_name='Článek'),
        ),
        migrations.AddField(
            model_name='zprava',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor zprávy'),
        ),
        migrations.AddField(
            model_name='diskuze',
            name='zpravy',
            field=models.ManyToManyField(related_name='diskuze', to='diskuze.zprava', verbose_name='Zprávy v diskuzi'),
        ),
    ]
