# Generated by Django 5.2.4 on 2025-07-26 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diskuze', '0003_remove_diskuze_clanek'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diskuze',
            name='clanek',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diskuze_ke_clanku', to='pages.page', verbose_name='Článek'),
        ),
    ]
