# Generated by Django 5.2.4 on 2025-07-26 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diskuze', '0004_diskuze_clanek'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diskuze',
            name='clanek',
        ),
    ]
