# Generated by Django 5.2.4 on 2025-07-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diskuze', '0005_remove_diskuze_clanek'),
    ]

    operations = [
        migrations.AddField(
            model_name='diskuze',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Datum aktualizace diskuze'),
        ),
    ]
