# Generated by Django 5.2.4 on 2025-07-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diskuze', '0006_diskuze_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zprava',
            options={'ordering': ['-datum_vytvoreni'], 'verbose_name': 'Zpráva', 'verbose_name_plural': 'Zprávy'},
        ),
        migrations.AlterField(
            model_name='zprava',
            name='nazev',
            field=models.CharField(blank=True, help_text='Název zprávy, pokud není zadán, použije se název diskuze.', max_length=200, null=True, verbose_name='Název zprávy'),
        ),
    ]
