# Generated by Django 5.2.4 on 2025-07-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diskuze', '0007_alter_zprava_options_alter_zprava_nazev'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zprava',
            name='nazev',
            field=models.CharField(default='Zpráva', max_length=200, null=True, verbose_name='Název zprávy'),
        ),
    ]
