# Generated by Django 5.2.4 on 2025-07-26 12:18

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diskuze', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(auto_created=True, error_messages={'blank': 'Identifikátor nesmí být prázdný.', 'unique': 'Tento identifikátor již existuje.'}, help_text='Identifikátor pro URL, automaticky generován z názvu stránky', unique=True, verbose_name='Identifikátor (slug)')),
                ('title', models.CharField(max_length=200, verbose_name='Název stránky')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Obsah')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Datum poslední úpravy')),
                ('diskuze', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='diskuze.diskuze', verbose_name='Diskuze')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
