# Generated by Django 5.2.4 on 2025-07-26 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_page_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='diskuze',
            new_name='diskuze_set',
        ),
    ]
